### ISSUE TITLE
莱可可你的 favicon 是不是忘记换了

### ISSUE THREAD

**Issue by xqm32** [RedContritio/RedContritio.github.io#13]
avatar 换了 favicon 为什么不换（生气😡）

avatar changed favicon why not (angry😡)

**Comment by RedContritio** [comment]
社交媒体的头像与昵称相对具有多变性以体现一定时期内的情感、思维状况，而技术相关平台不需要进行类似的改动。

The avatar and nickname of social media are relatively variable to reflect the emotions and thinking conditions in a certain period of time, and technology-related platforms DO NOT need to make similar changes.
